Map<String, String> avatarLocMap = {
  'department': 'assets/avatars/department.svg',
  'health': 'assets/avatars/health.svg',
  'police': 'assets/avatars/police.svg',
  'municipality': 'assets/avatars/municipality.svg',
  'transport': 'assets/avatars/transport.svg',
  'commerce': 'assets/avatars/commerce.svg',
  'tourism': 'assets/avatars/tourism.svg',
  'space': 'assets/avatars/space.svg',
  'railway': 'assets/avatars/railway.svg',
  'agriculture': 'assets/avatars/agriculture.svg',
};

Map<String, int> avatarColorMap = {
  'department': 0xffF7FBFF,
  'health': 0xffFFFAFA,
  'police': 0xffFFFEFA,
  'municipality': 0xffFBFAFF,
  'transport': 0xffFAFAFA,
  'commerce': 0xffFFFBFA,
  'tourism': 0xffFAFCFF,
  'space': 0xffFAFCFF,
  'railway': 0xffFFFAFA,
  'agriculture': 0xffFAFFFC,
};

Map<String, int> categoryTagColorMap = {
  'department': 0xff175FB4,
  'health': 0xffE2574C,
  'police': 0xffFFCE00,
  'municipality': 0xff3D17BC,
  'transport': 0xff777777,
  'commerce': 0xffB9785F,
  'tourism': 0xff55A4F9,
  'space': 0xff205B98,
  'railway': 0xffC03A2B,
  'agriculture': 0xff02A437,
};


List<String> imageFormats = [
  "jpg",
  "jpeg",
  "jpe",
  "jif",
  "jfif",
  "jfi",
  "png",
  "gif",
  "webp",
  "tiff",
  "tif",
  "psd",
  "raw",
  "arw",
  "cr2",
  "nrw",
  "k25",
  "bmp",
  "dib",
  "heif",
  "heic",
  "ind",
  "indd",
  "indt",
  "jp2",
  "j2k",
  "jpf",
  "jpx",
  "jpm",
  "mj2",
  "svg",
  "svgz",
  "ai",
  "eps"
];