/// Flutter icons AppBarIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppBarIcons
///      fonts:
///       - asset: fonts/AppBarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppBarIcons {
  AppBarIcons._();

  static const _kFontFam = 'AppBarIcons';
  static const _kFontPkg = null;

  static const IconData location = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
