/// Flutter icons BottomBarIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomBarIcons
///      fonts:
///       - asset: fonts/BottomBarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomBarIcons {
  BottomBarIcons._();

  static const _kFontFam = 'BottomBarIcons';
  static const _kFontPkg = null;

  static const IconData building = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
