/// Flutter icons DrawerIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DrawerIcons
///      fonts:
///       - asset: fonts/DrawerIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DrawerIcons {
  DrawerIcons._();

  static const _kFontFam = 'DrawerIcons';
  static const _kFontPkg = null;

  static const IconData privacy = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData general = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blacklist = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
